spring:
  profiles:
    active: local

  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      mode: always
      encoding: UTF-8

jwt:
  expiration: 604800000   # 7일 (ms)

server:
  port: 8080